export const CHANGE_HELLO = 'CHANGE_HELLO';
export const CHANGE_HELLO_REJECTED = 'CHANGE_HELLO_REJECTED';
export const CHANGE_HELLO_FULLFILED = 'CHANGE_HELLO_FULLFILED';

export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const LOAD_NOTIFICATION = 'LOAD_NOTIFICATION';
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION';

// export const CHANGE_HELLO_REJECTED = 'CHANGE_HELLO_REJECTED';
// export const CHANGE_HELLO_FULLFILED = 'CHANGE_HELLO_FULLFILED';
